### PR TITLE
feat: add redux-store

### PR DESCRIPTION
**Pull request by TimoGlastra**
## Description

Add initial move to extensions repo. Adds redux-store with mostly the same structure as AFJ. Main difference is that we're not using lerna, and we're also not using the same version strategy. It makes more sense to me to be able to separately develop packages.

I've had some struggles to be able to create releases, update versions etc to the main branch from within a CI script. So I've tested out a new approach that I think could work really well.

We keep PRs open for all packages and once we merge them a new release will be created based on conventional commits. This means we do need to follow conventional commits, but also means we have an easy way to publish packages. This is an open source tool from google, and is completely automated using Github actions.

See https://github.com/TimoGlastra/aries-framework-javascript-ext/pull/2 for an example

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] The commit message(s) follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Documentation has been added / updated (for bug fixes / features)
- [x] Changes follow the **[contributing](../CONTRIBUTING.md)** document.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Which merge strategy will you use?

- [ ] Squash (REVIEW PR title)
- [x] Rebase (REVIEW commit messages)

### CODE REVIEW

**Comment by TimoGlastra** [comment]
@JamesKEbert once this PR is merged and CI seems to be working, we can start to migrate the redux-hooks package

**Comment by karimStekelenburg** [comment]
Could you provide a link to that Google tool? Having a hard time understanding what is does based of your description 😊

**Comment by TimoGlastra** [comment]
https://github.com/googleapis/release-please

**Comment by TimoGlastra** [comment]
See this PR for an example of what it does: https://github.com/TimoGlastra/aries-framework-javascript-ext/pull/2

**Review by karimStekelenburg — APPROVED** [review]

**Pull request merged**
