### PR TITLE
chore!: update aries framework javascript version to 0.1.0

### PR DESCRIPTION
**Pull request by blu3beri**

### CODE REVIEW

**Review by TimoGlastra — APPROVED** [review]
Nice, LGTM 👍

**Comment by blu3beri** [comment]
Can I merge this?

**Comment by TimoGlastra** [comment]
Ci is failing, but otherwise yes!

**Comment by TimoGlastra** [comment]
@blu3beri can you fix the CI issues? I think increasing the timeout a bit could do the trick?

**Pull request merged**
