### PR TITLE
feat(react-hooks): support question answer module

### PR DESCRIPTION
**Pull request by seajensen**
This PR adds a react hook to work with the Question-Answer module.

### CODE REVIEW

**Review by JamesKEbert — APPROVED** [review]
LGTM

**Comment by JamesKEbert** [comment]
Probably just needs to be merged with main to re-trigger the checks

**Comment by TimoGlastra** [comment]
QA has been extracted out of core in 0.3, or is this PR still aimed for release on 0.2.x?

If QA is added, it means the agent must have registered the QA module for it to work. Are all providers registered by default? Maybe this one should be an add on?

**Comment by JamesKEbert** [comment]
Closed in favor of #193

**Pull request closed without merging**
